version: '2'
services:
# ======services======
  service-1:
    extends:
      file: Service-1.yml
      service: service-1
  service-2:
    extends:
      file: Service-2.yml
      service: service-2
  service-3:
    extends:
      file: Service-3.yml
      service: service-3
# ======traefik======
  traefik:
    extends:
      file: traefik.yml
      service: traefik